"""empty message

Revision ID: e327d78c0038
Revises: 5982c99da56e
Create Date: 2022-08-17 22:33:05.319065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e327d78c0038'
down_revision = '5982c99da56e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('login_history', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.alter_column('entry', 'street_address',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('entry', 'city',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('entry', 'state',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('entry', 'email',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entry', 'email',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('entry', 'state',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('entry', 'city',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('entry', 'street_address',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.drop_table('login_user')
    # ### end Alembic commands ###
